-- Destinations Data Dump
INSERT INTO `destinations` (`id`, `destination_name`, `region`, `destination_type`, `best_seasons`, `location`, `short_description`, `detailed_description`, `rating`, `reviews_count`, `badge`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES ('1', 'Dal Lake', 'kashmir', 'lake', '[\"spring\",\"summer\",\"autumn\"]', 'Srinagar', 'The jewel of Srinagar, famous for its houseboats, shikaras, and floating gardens.', 'Dal Lake is the jewel in the crown of Kashmir tourism. Spread over 18 square kilometers, this iconic lake is famous for its intricately carved houseboats, colorful shikaras (wooden boats), and floating vegetable gardens called \"Rad\". The lake is divided into four basins: Gagribal, Lokut Dal, Bod Dal and Nagin. Visitors can stay in luxurious houseboats, shop at floating markets, and experience the unique lifestyle of the lake dwellers.', '4.80', '342', 'Popular', '1', '1', '2025-12-18 12:18:44', '2025-12-19 12:33:58');
INSERT INTO `destinations` (`id`, `destination_name`, `region`, `destination_type`, `best_seasons`, `location`, `short_description`, `detailed_description`, `rating`, `reviews_count`, `badge`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES ('2', 'Pangong Lake', 'ladakh', 'lake', '[\"summer\"]', 'Changthang', 'Famous for its changing colors from blue to green to red.', 'Pangong Tso (Lake) is one of the most spectacular high-altitude lakes in the world, located at an elevation of 4,225 meters. Stretching 134 km from India to China, the lake is famous for its magical color-changing properties - from shades of blue and green to violet and red. The lake freezes completely during winter. Featured in the Bollywood movie \"3 Idiots\", it has become a must-visit destination for travelers seeking breathtaking landscapes.', '4.90', '289', 'Adventure', '1', '1', '2025-12-18 12:18:44', '2025-12-18 12:18:44');
INSERT INTO `destinations` (`id`, `destination_name`, `region`, `destination_type`, `best_seasons`, `location`, `short_description`, `detailed_description`, `rating`, `reviews_count`, `badge`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES ('3', 'Leh :  Land  of High Passes', 'ladakh', 'hill', '[\"summer\",\"winter\"]', 'Baramulla', 'Leh is the cultural capital of Ladakh, known for its monasteries, rugged landscapes, and thrilling road trips.', 'Gulmarg, meaning \"Meadow of Flowers\", is a world-class ski destination and the premier hill station of Kashmir. Located at 2,650 meters, it offers the highest gondola ride in the world reaching 3,980 meters at Apharwat Peak. In winter, it transforms into a skier\'s paradise with pristine powder snow. In summer, the meadows bloom with thousands of wildflowers, offering excellent opportunities for golfing, trekking, and nature walks.', '4.70', '456', 'Scenic', '1', '1', '2025-12-18 12:18:44', '2025-12-19 12:19:08');
INSERT INTO `destinations` (`id`, `destination_name`, `region`, `destination_type`, `best_seasons`, `location`, `short_description`, `detailed_description`, `rating`, `reviews_count`, `badge`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES ('6', 'Nubra Valley', 'ladakh', 'desert', '[\"summer\"]', 'Diskit', 'Cold desert valley famous for sand dunes, double-humped camels, and picturesque river confluence.', 'Nubra Valley, also called the \"Valley of Flowers\", is a high-altitude cold desert located 150 km north of Leh. The valley is famous for its white sand dunes, double-humped Bactrian camels, and the picturesque confluence of the Shyok and Nubra rivers. Visitors must cross the world\'s highest motorable road, Khardung La Pass (5,359m), to reach this magical valley. The Diskit Monastery with its 32-meter Maitreya Buddha statue overlooks the entire valley.', '4.90', '234', NULL, '1', '1', '2025-12-18 12:18:44', '2025-12-19 12:33:17');
INSERT INTO `destinations` (`id`, `destination_name`, `region`, `destination_type`, `best_seasons`, `location`, `short_description`, `detailed_description`, `rating`, `reviews_count`, `badge`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES ('8', 'Sonamarg', 'kashmir', 'adventure', '[\"spring\",\"summer\",\"autumn\",\"winter\"]', 'Ganderbal District, Kashmir', 'Sonamarg is known for its breathtaking glaciers, alpine meadows, and as a gateway to Ladakh via the Zoji La Pass.', '', '4.50', '58', 'Adventure', '1', '1', '2025-12-18 19:30:43', '2025-12-19 12:38:21');
INSERT INTO `destinations` (`id`, `destination_name`, `region`, `destination_type`, `best_seasons`, `location`, `short_description`, `detailed_description`, `rating`, `reviews_count`, `badge`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES ('11', 'Pahalgam', 'kashmir', 'valley', '[\"spring\",\"summer\",\"autumn\"]', 'Anantnag District, Kashmir', 'Pahalgam is a serene valley surrounded by pine forests and rivers, serving as a base for Amarnath Yatra and popular trekking routes.', '', '4.50', '140', '', '1', '1', '2025-12-18 20:15:54', '2025-12-19 12:35:45');
INSERT INTO `destinations` (`id`, `destination_name`, `region`, `destination_type`, `best_seasons`, `location`, `short_description`, `detailed_description`, `rating`, `reviews_count`, `badge`, `is_featured`, `is_active`, `created_at`, `updated_at`) VALUES ('14', 'Gulmarg', 'kashmir', 'hill', '[\"spring\",\"summer\",\"winter\"]', 'Baramulla District, Kashmir', 'Gulmarg is a world-famous hill station known for Asia???s highest cable car, lush green meadows, and premier skiing slopes, making it a year-round adventure destination.', '', '4.50', '100', 'Scenic', '1', '1', '2025-12-18 22:57:36', '2025-12-19 12:11:20');

-- Destination Images Data Dump
INSERT INTO `destination_images` (`id`, `destination_id`, `image_path`, `is_primary`, `caption`, `created_at`) VALUES ('9', '6', 'destinations/6944f8b5848b3_sourav-bhadra-0pnQv-E92Zo-unsplash.jpeg', '1', NULL, '2025-12-19 12:33:17');
INSERT INTO `destination_images` (`id`, `destination_id`, `image_path`, `is_primary`, `caption`, `created_at`) VALUES ('10', '1', 'destinations/6944f8ded26a3_naweedey-XHG0uFAlEGM-unsplash.jpeg', '1', NULL, '2025-12-19 12:33:58');
INSERT INTO `destination_images` (`id`, `destination_id`, `image_path`, `is_primary`, `caption`, `created_at`) VALUES ('11', '14', 'destinations/6944f904260d0_digjot-singh-Vkkg9XoUcZI-unsplash.jpeg', '1', NULL, '2025-12-19 12:34:36');
INSERT INTO `destination_images` (`id`, `destination_id`, `image_path`, `is_primary`, `caption`, `created_at`) VALUES ('12', '11', 'destinations/6944f949e6bb2_sourav-bhadra--zRhJ0V9vKI-unsplash.jpeg', '1', NULL, '2025-12-19 12:35:45');
INSERT INTO `destination_images` (`id`, `destination_id`, `image_path`, `is_primary`, `caption`, `created_at`) VALUES ('13', '2', 'destinations/6944f9a1f326b_hans-jurgen-mager-MrW_AqAFNR0-unsplash.jpeg', '1', NULL, '2025-12-19 12:37:13');
INSERT INTO `destination_images` (`id`, `destination_id`, `image_path`, `is_primary`, `caption`, `created_at`) VALUES ('14', '3', 'destinations/6944f9b52fc56_t2-graphy-IJfpVYlRv5I-unsplash.jpeg', '1', NULL, '2025-12-19 12:37:33');
INSERT INTO `destination_images` (`id`, `destination_id`, `image_path`, `is_primary`, `caption`, `created_at`) VALUES ('15', '8', 'destinations/6944f9e5c79e4_yasser-mir-iMnIu-GoEeE-unsplash.jpeg', '1', NULL, '2025-12-19 12:38:21');
INSERT INTO `destination_images` (`id`, `destination_id`, `image_path`, `is_primary`, `caption`, `created_at`) VALUES ('19', '14', 'destinations/696f57f73c18b_apple-crisp-bites.webp', '1', NULL, '2026-01-20 15:54:55');
INSERT INTO `destination_images` (`id`, `destination_id`, `image_path`, `is_primary`, `caption`, `created_at`) VALUES ('20', '14', 'destinations/696f57f742017_banana-crisp-bites.webp', '0', NULL, '2026-01-20 15:54:55');
INSERT INTO `destination_images` (`id`, `destination_id`, `image_path`, `is_primary`, `caption`, `created_at`) VALUES ('21', '14', 'destinations/696f57f743ac5_guava-crisp-bites.webp', '0', NULL, '2026-01-20 15:54:55');
INSERT INTO `destination_images` (`id`, `destination_id`, `image_path`, `is_primary`, `caption`, `created_at`) VALUES ('22', '14', 'destinations/696f57f746e25_pineapple-crisp-bites.webp', '0', NULL, '2026-01-20 15:54:55');
INSERT INTO `destination_images` (`id`, `destination_id`, `image_path`, `is_primary`, `caption`, `created_at`) VALUES ('23', '14', 'destinations/696f57f747c6c_strawberry-crisp-bites.webp', '0', NULL, '2026-01-20 15:54:55');

-- Highlights Data Dump


-- Activities Data Dump


-- Tips Data Dump


-- Nearby Attractions Data Dump


